name: Deploy Demo to GitHub Pages

on:
  push:
    branches: [ "main" ]  # Deploy on push to main branch
  workflow_dispatch:  # Allows manual triggering

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build demo project
      run: dotnet publish SophiChain.BlazorDatePicker.Demo/SophiChain.BlazorDatePicker.Demo.csproj --configuration Release --output ./publish

    - name: Change base-tag in index.html for GitHub Pages
      run: |
        if [ "${{ github.repository }}" != "${{ github.repository_owner }}/${{ github.repository_owner }}.github.io" ]; then
          REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)
          sed -i "s/<base href=\"\/\" \/>/<base href=\"\/$REPO_NAME\/\" \/>/g" ./publish/wwwroot/index.html
        fi
      shell: bash

    - name: Add .nojekyll file
      run: touch ./publish/wwwroot/.nojekyll

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './publish/wwwroot'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
